name: Feature Request
description: Suggest a new feature or enhancement for the Crypto Addiction Awareness app
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.
        
  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see.
      placeholder: What feature would you like to add?
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of the app does this feature relate to?
      options:
        - Crypto Price Tracking
        - Checking Frequency Analytics
        - Behavioral Insights
        - User Interface/Experience
        - Data Visualization
        - Notifications/Alerts
        - Settings/Configuration
        - Addiction Recovery Tools
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-benefit
    attributes:
      label: Primary User Benefit
      description: What is the main benefit this feature would provide?
      options:
        - Reduce checking frequency
        - Better awareness of habits
        - Improved data visualization
        - Enhanced user experience
        - More accurate tracking
        - Better addiction recovery support
        - Increased motivation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: What other approaches could solve this problem?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any additional information, screenshots, or examples...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Essential feature
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to contribute to implementing this feature
          required: false
        - label: I can provide detailed specifications or requirements
          required: false
        - label: I can help test the feature once implemented
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested yet
          required: true
        - label: This feature aligns with the goal of crypto addiction awareness and habit improvement
          required: true
        - label: I understand this is for a web application focused on tracking crypto checking frequency
          required: true